/**
 * 模拟数据源（仅开发环境）· V1-03 测试数据: a Feishu directory for 启衡精密.
 * The organisation matches 01-演示案例; members match the NocoHR employees by
 * employee number, 孙丽 included (she has no NocoHR account) and 邓凯
 * (emp_th_3, whose resignation V1-02 demonstrates). Two members
 * exist only in Feishu: 冯涛 (成都机加工车间, title 数控机床操作员 without a
 * mapping) and 唐宁 (技术中心, title 设备工程师, no matching position).
 *
 * The application writes this to storage/org-sync/feishu-mock.json on the
 * first sync when the file is missing; edit that file and sync again to
 * simulate changes in Feishu. Phone numbers are obvious test values.
 */
export const DEMO_DIRECTORY = {
  departments: [
    { id: 'fs-root', name: '启衡精密', parentId: null, managerUserId: null },
    {
      id: 'fs-hr',
      name: '人力资源部',
      parentId: 'fs-root',
      managerUserId: null,
    },
    {
      id: 'fs-quality',
      name: '质量部',
      parentId: 'fs-root',
      managerUserId: null,
    },
    {
      id: 'fs-tech',
      name: '技术中心',
      parentId: 'fs-root',
      managerUserId: null,
    },
    {
      id: 'fs-ops',
      name: '生产运营部',
      parentId: 'fs-root',
      managerUserId: null,
    },
    {
      id: 'fs-sz',
      name: '苏州工厂',
      parentId: 'fs-ops',
      managerUserId: 'fs-u-mgr-east',
    },
    {
      id: 'fs-sz-mc',
      name: '机加工车间',
      parentId: 'fs-sz',
      managerUserId: 'fs-u-mgr-njl',
    },
    {
      id: 'fs-sz-as',
      name: '装配车间',
      parentId: 'fs-sz',
      managerUserId: null,
    },
    {
      id: 'fs-cd',
      name: '成都工厂',
      parentId: 'fs-ops',
      managerUserId: 'fs-u-mgr-cd',
    },
    {
      id: 'fs-cd-mc',
      name: '成都机加工车间',
      parentId: 'fs-cd',
      managerUserId: null,
    },
  ],
  members: [
    {
      userId: 'fs-u-hr01',
      name: '林晓',
      employeeNo: 'QH1001',
      email: 'hr01@qiheng.test',
      mobile: '13900000001',
      departmentId: 'fs-hr',
      title: 'HR 专员',
      managerUserId: null,
      active: true,
    },
    {
      userId: 'fs-u-trainer01',
      name: '郑老师',
      employeeNo: 'QH1006',
      email: 'trainer01@qiheng.test',
      mobile: '13900000008',
      departmentId: 'fs-hr',
      title: '培训专员',
      managerUserId: null,
      active: true,
    },
    {
      userId: 'fs-u-mgr-east',
      name: '周宏',
      employeeNo: 'QH1002',
      email: 'mgr.east@qiheng.test',
      mobile: '13900000002',
      departmentId: 'fs-sz',
      title: '厂长',
      managerUserId: null,
      active: true,
    },
    {
      userId: 'fs-u-mgr-njl',
      name: '陈静',
      employeeNo: 'QH1003',
      email: 'mgr.njl@qiheng.test',
      mobile: '13900000003',
      departmentId: 'fs-sz-mc',
      title: '车间主任',
      managerUserId: 'fs-u-mgr-east',
      active: true,
    },
    {
      userId: 'fs-u-mgr-cd',
      name: '何伟',
      employeeNo: 'QH1004',
      email: 'mgr.cd@qiheng.test',
      mobile: '13900000011',
      departmentId: 'fs-cd',
      title: '厂长',
      managerUserId: null,
      active: true,
    },
    {
      userId: 'fs-u-wanglei',
      name: '王磊',
      employeeNo: 'QH2001',
      email: 'emp.njl.1@qiheng.test',
      mobile: '13900000004',
      departmentId: 'fs-sz-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-njl',
      active: true,
    },
    {
      userId: 'fs-u-limin',
      name: '李敏',
      employeeNo: 'QH2002',
      email: 'emp.njl.2@qiheng.test',
      mobile: '13900000005',
      departmentId: 'fs-sz-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-njl',
      active: true,
    },
    {
      userId: 'fs-u-qianjin',
      name: '钱进',
      employeeNo: 'QH2003',
      email: 'emp.njl.3@qiheng.test',
      mobile: '13900000010',
      departmentId: 'fs-sz-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-njl',
      active: true,
    },
    {
      userId: 'fs-u-liuyang',
      name: '刘洋',
      employeeNo: 'QH2004',
      email: 'emp.njl.4@qiheng.test',
      mobile: '13900000012',
      departmentId: 'fs-sz-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-njl',
      active: true,
    },
    {
      userId: 'fs-u-sunli',
      name: '孙丽',
      employeeNo: 'QH2101',
      email: null,
      mobile: '13900000007',
      departmentId: 'fs-sz-as',
      title: '装配工',
      managerUserId: 'fs-u-mgr-east',
      active: true,
    },
    {
      userId: 'fs-u-zhaoyang',
      name: '赵阳',
      employeeNo: 'QH3001',
      email: 'emp.th.1@qiheng.test',
      mobile: '13900000006',
      departmentId: 'fs-cd-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-cd',
      active: true,
    },
    {
      userId: 'fs-u-wumin',
      name: '吴敏',
      employeeNo: 'QH3002',
      email: 'emp.th.2@qiheng.test',
      mobile: '13900000009',
      departmentId: 'fs-cd-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-cd',
      active: true,
    },
    {
      // 邓凯 (emp_th_3, V1-01 realigned): bound by employee number like the others.
      userId: 'fs-u-dengkai',
      name: '邓凯',
      employeeNo: 'QH3004',
      email: 'emp.th.3@qiheng.test',
      mobile: '13900000012',
      departmentId: 'fs-cd-mc',
      title: 'CNC 操作工',
      managerUserId: 'fs-u-mgr-cd',
      active: true,
    },
    {
      userId: 'fs-u-fengtao',
      name: '冯涛',
      employeeNo: null,
      email: 'fengtao@qiheng.test',
      mobile: '13900000021',
      departmentId: 'fs-cd-mc',
      title: '数控机床操作员',
      managerUserId: 'fs-u-mgr-cd',
      active: true,
    },
    {
      userId: 'fs-u-tangning',
      name: '唐宁',
      employeeNo: null,
      email: 'tangning@qiheng.test',
      mobile: '13900000022',
      departmentId: 'fs-tech',
      title: '设备工程师',
      managerUserId: null,
      active: true,
    },
  ],
};

/** The confirmed mappings V1-03 seeds (manual): the Feishu titles the demo uses. */
export const DEMO_POSITION_ALIASES = [
  ['CNC 操作工', 'pos-cnc-operator'],
  ['装配工', 'pos-assembler'],
  ['车间主任', 'pos-workshop-lead'],
  ['厂长', 'pos-plant-director'],
  ['HR 专员', 'pos-office-hr'],
  // Not in the spec's list, but 郑老师 (added by the learning step) holds this title.
  ['培训专员', 'pos-office-trainer'],
] as const;
